In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

In [2]:
cm = [[188,0,0,62,  31   4 106   8   3 339   0   9   0   0   0   0]
 [  9  17   0  89  61   3 173  66  18 229  21  46   0  17   1   0]
 [ 10   0  19   7  29   0 461   3   0 221   0   0   0   0   0   0]
 [  2   1   0 571  41   1  17   0   3 110   0   3   0   1   0   0]
 [  0   0   0  21 330   2  16   1   6  75   0   0   0   0   0   0]
 [ 15   0   0  30  11  16 301  20  14 331   4   2   0   4   0   2]
 [  0   0   0   4  10   5 631   0   4  96   0   0   0   0   0   0]
 [  7   4   0  21  19   0 197 223   2 266   2   6   0   3   0   0]
 [  0   0   0   7  23   1 310   0 181 228   0   0   0   0   0   0]
 [  0   0   0   9  29   2  49   3   3 652   1   0   0   2   0   0]
 [  6   0   0  18  16   1 165  41  16 418  56   9   0   4   0   0]
 [  9   6   0  32  19   0 160  17  12 360   8 126   0   1   0   0]
 [ 14   0   0  54  35   4  93   8  14 517   2   5   3   1   0   0]
 [ 11   1   0  71  62   3 240  42  15 243   1  28   0  32   0   0]
 [ 53   4   0  38  17   5 228  21  11 212   1  11   0   7 142   0]
 [ 39   0   0  24  19   0 169   9   1 472   0  10   0   2   0   5]]

SyntaxError: invalid syntax (<ipython-input-2-0c5e2c05a837>, line 1)

In [ ]:
def cm_analysis(y_true, y_pred, filename, labels, ymap=None, figsize=(10,10)):

    cm_sum = np.sum(cm, axis=1, keepdims=True)
    cm_perc = cm / cm_sum.astype(float) * 100
    annot = np.empty_like(cm).astype(str)
    nrows, ncols = cm.shape
    for i in range(nrows):
        for j in range(ncols):
            c = cm[i, j]
            p = cm_perc[i, j]
            if i == j:
                s = cm_sum[i]
                annot[i, j] = '%.1f%%\n%d/%d' % (p, c, s)
            elif c == 0:
                annot[i, j] = ''
            else:
                annot[i, j] = '%.1f%%\n%d' % (p, c)
    cm = pd.DataFrame(cm, index=labels, columns=labels)
    cm.index.name = 'Actual'
    cm.columns.name = 'Predicted'
    fig, ax = plt.subplots(figsize=figsize)
    sns.heatmap(cm, annot=annot, fmt='', ax=ax)
    plt.savefig(filename)